# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 2aeecd2b6846924e993e0c7f72b2e6dc6370eaf1e5c7c294dad40be6ef07398b11363eeb5d51bf58a6f7fbf753ca7d2609120d493a82ea98737ea3cd4271230b

test:
  secret_key_base: 0d91b63c6c9b7057ed051ebec13c60c6dd70de90d12380cbc58ec5793aa78112c6d1444e61e3d1657897338786738e6b59f7596ce7eeb3316c5df345d54c23c0

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
