# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 9a353eba02eafc4397d280e9e8e7e1724c5c13b08e7a71a1dcf2310390f6837acab2bbe707729cd71fceca04273e14107392f792084260a073665460375efc23

test:
  secret_key_base: 2745fae5138169f299aa9e4dc33a6d93d45da0f5dfc5ec20e60a0d8456abdd5375bfe44da5a83f62aa33df81ac4be88070cf9e3de0b2d3a737c7459ec717607b

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
